/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	azurequeuev1alpha1 "github.com/patnaikshekhar/AzureStorageQueueOperator/pkg/apis/azurequeue/v1alpha1"
	versioned "github.com/patnaikshekhar/AzureStorageQueueOperator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/patnaikshekhar/AzureStorageQueueOperator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/patnaikshekhar/AzureStorageQueueOperator/pkg/client/listers/azurequeue/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AzureQueueInformer provides access to a shared informer and lister for
// AzureQueues.
type AzureQueueInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AzureQueueLister
}

type azureQueueInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAzureQueueInformer constructs a new informer for AzureQueue type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAzureQueueInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAzureQueueInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAzureQueueInformer constructs a new informer for AzureQueue type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAzureQueueInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzureV1alpha1().AzureQueues(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzureV1alpha1().AzureQueues(namespace).Watch(options)
			},
		},
		&azurequeuev1alpha1.AzureQueue{},
		resyncPeriod,
		indexers,
	)
}

func (f *azureQueueInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAzureQueueInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *azureQueueInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&azurequeuev1alpha1.AzureQueue{}, f.defaultInformer)
}

func (f *azureQueueInformer) Lister() v1alpha1.AzureQueueLister {
	return v1alpha1.NewAzureQueueLister(f.Informer().GetIndexer())
}
