apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagequeues.azure.microsoft.com
spec:
  group: azure.microsoft.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Cluster
  names:
    plural: storagequeues
    singular: storagequeue
    kind: StorageQueue
    shortNames:
    - azsq
  