/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/patnaikshekhar/azure_queue_operator/pkg/apis/azurequeue/v1alpha1"
	scheme "github.com/patnaikshekhar/azure_queue_operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AzureQueuesGetter has a method to return a AzureQueueInterface.
// A group's client should implement this interface.
type AzureQueuesGetter interface {
	AzureQueues(namespace string) AzureQueueInterface
}

// AzureQueueInterface has methods to work with AzureQueue resources.
type AzureQueueInterface interface {
	Create(*v1alpha1.AzureQueue) (*v1alpha1.AzureQueue, error)
	Update(*v1alpha1.AzureQueue) (*v1alpha1.AzureQueue, error)
	UpdateStatus(*v1alpha1.AzureQueue) (*v1alpha1.AzureQueue, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AzureQueue, error)
	List(opts v1.ListOptions) (*v1alpha1.AzureQueueList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AzureQueue, err error)
	AzureQueueExpansion
}

// azureQueues implements AzureQueueInterface
type azureQueues struct {
	client rest.Interface
	ns     string
}

// newAzureQueues returns a AzureQueues
func newAzureQueues(c *FooV1alpha1Client, namespace string) *azureQueues {
	return &azureQueues{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the azureQueue, and returns the corresponding azureQueue object, and an error if there is any.
func (c *azureQueues) Get(name string, options v1.GetOptions) (result *v1alpha1.AzureQueue, err error) {
	result = &v1alpha1.AzureQueue{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azurequeues").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzureQueues that match those selectors.
func (c *azureQueues) List(opts v1.ListOptions) (result *v1alpha1.AzureQueueList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AzureQueueList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("azurequeues").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azureQueues.
func (c *azureQueues) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("azurequeues").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a azureQueue and creates it.  Returns the server's representation of the azureQueue, and an error, if there is any.
func (c *azureQueues) Create(azureQueue *v1alpha1.AzureQueue) (result *v1alpha1.AzureQueue, err error) {
	result = &v1alpha1.AzureQueue{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("azurequeues").
		Body(azureQueue).
		Do().
		Into(result)
	return
}

// Update takes the representation of a azureQueue and updates it. Returns the server's representation of the azureQueue, and an error, if there is any.
func (c *azureQueues) Update(azureQueue *v1alpha1.AzureQueue) (result *v1alpha1.AzureQueue, err error) {
	result = &v1alpha1.AzureQueue{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azurequeues").
		Name(azureQueue.Name).
		Body(azureQueue).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *azureQueues) UpdateStatus(azureQueue *v1alpha1.AzureQueue) (result *v1alpha1.AzureQueue, err error) {
	result = &v1alpha1.AzureQueue{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("azurequeues").
		Name(azureQueue.Name).
		SubResource("status").
		Body(azureQueue).
		Do().
		Into(result)
	return
}

// Delete takes name of the azureQueue and deletes it. Returns an error if one occurs.
func (c *azureQueues) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azurequeues").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azureQueues) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("azurequeues").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched azureQueue.
func (c *azureQueues) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AzureQueue, err error) {
	result = &v1alpha1.AzureQueue{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("azurequeues").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
